### ISSUE TITLE
TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Metadata.IRelationalEntityTypeAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### ISSUE THREAD

**Issue by BlackFenix2** [neurospeech/asp-net-core-extensions#5]
When i try to run this project on .net core 3 i get this error:

```
TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Metadata.IRelationalEntityTypeAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```
i noticed that your project was not dumped to .net core 3, i can submit a PR to bump this project and packages.

**Comment by ackava** [comment]
@BlackFenix2 PR is welcome, our internal projects are still running on .net 2 so we haven't made massive changes, but I suspect EF core 3 changes might create issues. Let me know if you face any issue.

**Comment by ackava** [comment]
@BlackFenix2 We have started upgrading to 3, lot of APIs have changed so it will take some time.

**Comment by ackava** [comment]
@BlackFenix2 Libraries are now upgraded to .NET Core 3.0, please try and let us know if you are getting any other error.

**Comment by BlackFenix2** [comment]
That Fixed the issue! i can live migrate my blazor app now!
